### ISSUE TITLE
Redmine user management Plugin compatibility

### ISSUE THREAD

**Issue by jcdelacernajr** [fredsdc/redmine_user_management#2]
Hello Good Day,

I having a issue while installing this plugin. Using  redmine version 4.0.3 
I know this plugin is not compatible in redmine version 4.0.3

Is there any hacky ways to install this plugin and make it compatible to version 4.0.3?. Just hoping  
I never used this before think this plugin has nice functionality and it fits to my needs.

Thank you.

**Comment by fredsdc** [comment]
Hi,

What issues are you having? It fails install, gives any error messages?

I don't think the redmine infrastructure from 4.x onwards have changed to the point this plugin would give install errors.

Maybe it's rails or ruby version.

Best regards,

**Comment by jcdelacernajr** [comment]
Thank you for you reply, I think there was a problem when migrating the database.
By the way I am using Windows

And  my MySql, Rails and Ruby installed

```
C:\Bitnami\redmine-4.0.3-2>mysql -V
mysql  Ver 14.14 Distrib 5.7.23, for Win64 (x86_64)

C:\Bitnami\redmine-4.0.3-2>rails -v
Rails 6.1.4

C:\Bitnami\redmine-4.0.3-2>ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
```

Here's the console error. Its says rake aborted

```
C:\Bitnami\redmine-4.0.3-2>set RAILS_ENV="production"

C:\Bitnami\redmine-4.0.3-2>bundle exec rake redmine:plugins:migrate NAME=redmine_user_management
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
(See full trace by running task with --trace)
```

Here the production log file

```
Processing by WelcomeController#index as HTML
  Current user: mdonaire (id=105)
  Rendering welcome/index.html.erb within layouts/base
  Rendered welcome/index.html.erb within layouts/base (2.6ms)
Completed 500 Internal Server Error in 76ms (ActiveRecord: 9.2ms)
  
ActionView::Template::Error (Mysql2::Error: Table 'bitnami_redmine.user_managers' doesn't exist: SELECT `user_managers`.* FROM `user_managers`):
    63: <div id="top-menu">
    64:     <div id="account">
    65:         <%= render_menu :account_menu -%>
    66:     </div>
    67:     <%= content_tag('div', "#{l(:label_logged_as)} #{link_to_user(User.current, :format => :username)}".html_safe, :id => 'loggedas') if User.current.logged? %>
    68:     <%= render_menu :top_menu if User.current.logged? || !Setting.login_required? -%>
    69: </div>
  
plugins/redmine_user_management/init.rb:32:in `map'
plugins/redmine_user_management/init.rb:32:in `block (2 levels) in <top (required)>'
lib/redmine/menu_manager.rb:484:in `allowed?'
lib/redmine/menu_manager.rb:195:in `block in menu_items_for'
lib/redmine/menu_manager.rb:194:in `each'
lib/redmine/menu_manager.rb:194:in `menu_items_for'
lib/redmine/menu_manager.rb:113:in `render_menu'
app/views/layouts/base.html.erb:66:in `_app_views_layouts_base_html_erb__595051100_97335880'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by jcdelacernajr** [comment]
Hello,

I checked the System, I think no rails installed or the rails version was outdated.

I run the command
`
C:\Bitnami\redmine-4.0.3-2>gem install rails
`

After the rails installation done.

`C:\Bitnami\redmine-4.0.3-2\apps\redmine\htdocs>set RAILS_ENV=production`
`C:\Bitnami\redmine-4.0.3-2\apps\redmine\htdocs>bundle exec rake redmine:plugins:migrate NAME=redmine_user_management`

```
== 20210312112620 CreateUserManagers: migrating ===============================
-- create_table(:user_managers)
   -> 0.1097s
== 20210312112620 CreateUserManagers: migrated (0.1105s) ======================

== 20210312112758 CreateUserManagerUcfs: migrating ============================
-- create_table(:user_manager_ucfs)
   -> 0.0468s
== 20210312112758 CreateUserManagerUcfs: migrated (0.0473s) ===================

== 20210312112938 CreateUserManagerGroups: migrating ==========================
-- create_table(:user_manager_groups)
   -> 0.0384s
== 20210312112938 CreateUserManagerGroups: migrated (0.0390s) =================

== 20210312113042 CreateUserManagerUsers: migrating ===========================
-- create_table(:user_manager_users)
   -> 0.0436s
== 20210312113042 CreateUserManagerUsers: migrated (0.0447s) ==================
```

And now the table is created. And the plugin is successfully installed

And also you must strictly type this command `set RAILS_ENV=production` without a trailing space and quotes. 
See on https://stackoverflow.com/questions/31999625/getting-config-eager-load-is-set-to-nil-while-trying-to-run-rails-c-in-test

Thank you.

**Comment by fredsdc** [comment]
You're welcome.
